import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useLocalSearchParams, router } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useColors } from '@/hooks/useColors';
import { useStore, statusLabels } from '@/context/AppContext';
export default function SchoolDetail() { const c = useColors(); const insets = useSafeAreaInsets(); const { id } = useLocalSearchParams<{ id: string }>(); const { schools, visits } = useStore(); const school = schools.find(s => s.id === id); const schoolVisits = visits.filter(v => v.schoolId === id); if (!school) return null; return <View style={[styles.page, { backgroundColor: c.background }]}><View style={[styles.header, { paddingTop: insets.top + 12 }]}><Pressable onPress={() => router.back()}><Feather name="arrow-right" size={23} color={c.foreground} /></Pressable><Text style={[styles.headerTitle, { color: c.foreground }]}>ملف المدرسة</Text><Pressable onPress={() => router.push({ pathname: '/school-form', params: { id: school.id } })}><Feather name="edit-2" size={20} color={c.primary} /></Pressable></View><ScrollView contentContainerStyle={{ paddingBottom: 40 }}><View style={[styles.cover, { backgroundColor: c.navy }]}><View style={[styles.schoolIcon, { backgroundColor: c.accent }]}><Feather name="home" size={26} color={c.navy} /></View><Text style={styles.schoolName}>{school.name}</Text><Text style={styles.address}>{school.address}</Text></View><Info label="المدير" value={school.director || 'غير مسجل'} c={c} /><Info label="المعاون الإداري" value={school.adminDeputy || 'غير مسجل'} c={c} /><Info label="المعاون الفني" value={school.technicalDeputy || 'غير مسجل'} c={c} /><Info label="معاون شؤون الطلبة" value={school.studentsDeputy || 'غير مسجل'} c={c} /><Text style={[styles.section, { color: c.foreground }]}>أقسام المدرسة</Text><View style={styles.tags}>{school.sections.map(s => <View key={s} style={[styles.tag, { backgroundColor: c.secondary }]}><Text style={{ color: c.secondaryForeground, fontFamily: 'Inter_500Medium', fontSize: 11 }}>{s}</Text></View>)}</View><Text style={[styles.section, { color: c.foreground }]}>سجل الزيارات ({schoolVisits.length})</Text>{schoolVisits.map(v => <View key={v.id} style={[styles.visit, { backgroundColor: c.card, borderColor: c.border }]}><View style={{ flex: 1 }}><Text style={[styles.visitTitle, { color: c.foreground }]}>{v.type}</Text><Text style={[styles.visitSub, { color: c.mutedForeground }]}>{v.date} · {v.reason}</Text></View><Text style={{ color: v.status === 'completed' ? c.success : c.warning, fontFamily: 'Inter_600SemiBold', fontSize: 10 }}>{statusLabels[v.status]}</Text></View>)}</ScrollView></View>; }
function Info({ label, value, c }: any) { return <View style={[styles.info, { backgroundColor: c.card, borderColor: c.border }]}><Text style={[styles.infoValue, { color: c.foreground }]}>{value}</Text><Text style={[styles.infoLabel, { color: c.mutedForeground }]}>{label}</Text></View>; }
const styles = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 18 }, header: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', paddingBottom: 16 }, headerTitle: { fontFamily: 'Inter_700Bold', fontSize: 20 }, cover: { borderRadius: 22, padding: 20, alignItems: 'center', marginBottom: 14 }, schoolIcon: { width: 56, height: 56, borderRadius: 19, alignItems: 'center', justifyContent: 'center', marginBottom: 10 }, schoolName: { color: '#fff', fontFamily: 'Inter_700Bold', fontSize: 18, textAlign: 'center' }, address: { color: '#B7D9D4', fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 6 }, info: { borderWidth: 1, borderRadius: 15, padding: 12, flexDirection: 'row-reverse', justifyContent: 'space-between', marginBottom: 8 }, infoValue: { fontFamily: 'Inter_600SemiBold', fontSize: 12 }, infoLabel: { fontFamily: 'Inter_400Regular', fontSize: 11 }, section: { fontFamily: 'Inter_700Bold', fontSize: 16, textAlign: 'right', marginTop: 18, marginBottom: 10 }, tags: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 7 }, tag: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 9 }, visit: { borderWidth: 1, borderRadius: 15, padding: 12, flexDirection: 'row-reverse', alignItems: 'center', gap: 8, marginBottom: 8 }, visitTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 12, textAlign: 'right' }, visitSub: { fontFamily: 'Inter_400Regular', fontSize: 10, textAlign: 'right', marginTop: 4 } });
