import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useColors } from '@/hooks/useColors';
import { useStore } from '@/context/AppContext';
export default function TaskForm() { const c = useColors(); const insets = useSafeAreaInsets(); const { schools, addTask } = useStore(); const [title, setTitle] = useState(''); const [time, setTime] = useState('09:00'); const [notes, setNotes] = useState(''); const [schoolId, setSchoolId] = useState<string | undefined>(); const [priority, setPriority] = useState<'high'|'medium'|'low'>('medium'); const save = () => { if (!title.trim()) return Alert.alert('بيانات ناقصة', 'اكتب عنوان العمل'); addTask({ title, time, notes, schoolId, priority, done: false, date: '2026-08-20' }); router.back(); }; return <View style={[styles.page, { backgroundColor: c.background }]}><View style={[styles.header, { paddingTop: insets.top + 12 }]}><Pressable onPress={() => router.back()}><Feather name="arrow-right" size={23} color={c.foreground} /></Pressable><Text style={[styles.title, { color: c.foreground }]}>إضافة عمل يومي</Text><View style={{ width: 24 }} /></View><ScrollView contentContainerStyle={{ paddingBottom: 45 }}><Field label="المهمة" value={title} onChangeText={setTitle} placeholder="مثال: متابعة سجل المدرسة" c={c} /><Field label="الوقت" value={time} onChangeText={setTime} placeholder="09:00" c={c} /><Text style={[styles.label, { color: c.foreground }]}>الأولوية</Text><View style={styles.row}>{(['high','medium','low'] as const).map(p => <Pressable key={p} onPress={() => setPriority(p)} style={[styles.option, { backgroundColor: priority === p ? c.secondary : c.card, borderColor: priority === p ? c.primary : c.border }]}><Text style={{ color: priority === p ? c.primary : c.foreground, fontFamily: 'Inter_600SemiBold', fontSize: 11 }}>{p === 'high' ? 'عالية' : p === 'medium' ? 'متوسطة' : 'منخفضة'}</Text></Pressable>)}</View><Text style={[styles.label, { color: c.foreground }]}>المدرسة المرتبطة</Text><View style={styles.wrap}>{schools.map(s => <Pressable key={s.id} onPress={() => setSchoolId(s.id)} style={[styles.option, { backgroundColor: schoolId === s.id ? c.primary : c.card, borderColor: schoolId === s.id ? c.primary : c.border }]}><Text style={{ color: schoolId === s.id ? c.primaryForeground : c.foreground, fontFamily: 'Inter_500Medium', fontSize: 11 }}>{s.name}</Text></Pressable>)}</View><Field label="ملاحظات" value={notes} onChangeText={setNotes} placeholder="أضف ملاحظاتك" c={c} multiline /><Pressable onPress={save} style={[styles.save, { backgroundColor: c.primary }]}><Feather name="check" size={19} color={c.primaryForeground} /><Text style={{ color: c.primaryForeground, fontFamily: 'Inter_700Bold' }}>حفظ العمل</Text></Pressable></ScrollView></View>; }
function Field({ label, value, onChangeText, placeholder, multiline, c }: any) { return <View style={styles.field}><Text style={[styles.label, { color: c.foreground }]}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={c.mutedForeground} multiline={multiline} style={[styles.input, { backgroundColor: c.card, borderColor: c.border, color: c.foreground, minHeight: multiline ? 90 : 48 }]} textAlign="right" textAlignVertical={multiline ? 'top' : 'center'} /></View>; }
const styles = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 18 }, header: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', paddingBottom: 16 }, title: { fontFamily: 'Inter_700Bold', fontSize: 20 }, field: { marginBottom: 7 }, label: { fontFamily: 'Inter_600SemiBold', fontSize: 12, textAlign: 'right', marginBottom: 8, marginTop: 8 }, input: { borderWidth: 1, borderRadius: 13, paddingHorizontal: 13, paddingVertical: 11, fontFamily: 'Inter_400Regular', fontSize: 13 }, row: { flexDirection: 'row-reverse', gap: 8 }, wrap: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 7 }, option: { borderWidth: 1, borderRadius: 11, paddingHorizontal: 11, paddingVertical: 10 }, save: { minHeight: 52, borderRadius: 15, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 20 } });
