import React, { useEffect, useMemo, useState } from 'react';
import { Image, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { useStore } from '@/context/AppContext';
import { KeyboardAwareScrollViewCompat } from '@/components/KeyboardAwareScrollViewCompat';
import { ZoomableImage } from '@/components/ZoomableImage';

const asString=(v?:string|string[]|null)=>Array.isArray(v)?v[0]??'':v?.toString()??'';
function section(text:string,heads:string[]){const s=String(text||'');for(const h of heads){const m=`${h}:`;const i=s.indexOf(m);if(i>=0){const r=s.slice(i+m.length);const n=r.search(/\n\n(?:الإجراءات المتخذة فعليًا|الإجراءات|التوصيات|التوصيات والإجراءات المقترحة|المتابعة|خطة المتابعة):/);return(n>=0?r.slice(0,n):r).trim();}}return'';}
function parseActions(text:string){return section(text,['الإجراءات المتخذة فعليًا','الإجراءات']);}
function parseRecommendations(text:string){return section(text,['التوصيات','التوصيات والإجراءات المقترحة']);}
function parseFollowUp(text:string){return section(text,['المتابعة','خطة المتابعة']);}
function structured(a:string,r:string,f:string){return [['الإجراءات المتخذة فعليًا',a],['التوصيات',r],['المتابعة',f]].filter(([,v])=>String(v||'').trim()).map(([h,v])=>`${h}:\n${String(v).trim()}`).join('\n\n');}

export default function VisitForm(){
 const c=useColors();const insets=useSafeAreaInsets();const {schools,visits,addVisit,updateVisit}=useStore();
 const params=useLocalSearchParams<{visitId?:string;schoolId?:string;date?:string;type?:string;visitType?:string;aiActions?:string;aiRecommendations?:string;aiFollowUp?:string}>();
 const edit=Boolean(params.visitId);const [schoolId,setSchoolId]=useState(asString(params.schoolId)||schools?.[0]?.id||'');const [date,setDate]=useState(asString(params.date)||new Date().toISOString().slice(0,10));const [type,setType]=useState(asString(params.type||params.visitType));const [actions,setActions]=useState(asString(params.aiActions));const [recommendations,setRecommendations]=useState(asString(params.aiRecommendations));const [followUp,setFollowUp]=useState(asString(params.aiFollowUp));const [photoUris,setPhotoUris]=useState<string[]>([]);const [preview,setPreview]=useState<string|null>(null);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [messageType,setMessageType]=useState<'error'|'success'|''>('');
 const existing=useMemo(()=>params.visitId?visits.find(v=>v.id===String(params.visitId)):undefined,[params.visitId,visits]);const selected=useMemo(()=>schools.find(s=>s.id===schoolId),[schools,schoolId]);
 useEffect(()=>{if(!existing)return;setSchoolId(String(existing.schoolId));setDate(String(existing.date));setType(String(existing.type||''));setActions(parseActions(String(existing.actions||''))||String(existing.actions||''));setRecommendations(parseRecommendations(String((existing as any).recommendations||'')));setFollowUp(parseFollowUp(String((existing as any).followUp||'')));const p=Array.isArray((existing as any).photoUris)?(existing as any).photoUris.filter(Boolean).map(String):[];if((existing as any).photoUri&&!p.includes((existing as any).photoUri))p.unshift((existing as any).photoUri);setPhotoUris(p);},[existing]);
 useEffect(()=>{if(params.aiActions!==undefined)setActions(asString(params.aiActions));if(params.aiRecommendations!==undefined)setRecommendations(asString(params.aiRecommendations));if(params.aiFollowUp!==undefined)setFollowUp(asString(params.aiFollowUp));if(params.type!==undefined||params.visitType!==undefined)setType(asString(params.type||params.visitType));},[params.aiActions,params.aiRecommendations,params.aiFollowUp,params.type,params.visitType]);
 const clearError=()=>{if(messageType==='error'){setMessage('');setMessageType('');}};
 const addPhotos=async()=>{try{const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted){setMessage('يرجى السماح للتطبيق بالوصول إلى الصور.');setMessageType('error');return;}const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.8,allowsMultipleSelection:true,selectionLimit:20});if(!r.canceled&&r.assets?.length){setPhotoUris(o=>Array.from(new Set([...o,...r.assets.map(a=>a.uri)])));clearError();}}catch(e){console.error(e);setMessage('تعذر اختيار الصور.');setMessageType('error');}};
 const takePhoto=async()=>{try{const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){setMessage('يرجى السماح للتطبيق باستخدام الكاميرا.');setMessageType('error');return;}const r=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.8,allowsEditing:true});if(!r.canceled&&r.assets?.[0]?.uri){setPhotoUris(o=>Array.from(new Set([...o,r.assets[0].uri])));clearError();}}catch(e){console.error(e);setMessage('تعذر فتح الكاميرا.');setMessageType('error');}};
 const openAI=()=>{if(!schoolId){setMessage('يرجى اختيار المدرسة أولًا.');setMessageType('error');return;}if(!type.trim()){setMessage('يرجى إدخال نوع الزيارة أولًا.');setMessageType('error');return;}router.push({pathname:'/visit-ai',params:{visitId:asString(params.visitId),schoolId:String(schoolId),schoolName:selected?.name||'',visitType:type.trim(),type:type.trim(),date:String(date)}});};
 const save=async()=>{if(saving)return;setMessage('');setMessageType('');if(!schoolId){setMessage('يرجى اختيار المدرسة أولًا.');setMessageType('error');return;}if(!date.trim()){setMessage('يرجى إدخال تاريخ الزيارة.');setMessageType('error');return;}if(!type.trim()){setMessage('يرجى إدخال نوع الزيارة.');setMessageType('error');return;}if(!actions.trim()){setMessage('يرجى إدخال الإجراءات الفعلية واعتمادها قبل الحفظ.');setMessageType('error');return;}try{setSaving(true);const data:any={schoolId:String(schoolId),date:date.trim(),type:type.trim(),actions:structured(actions,recommendations,followUp),recommendations:recommendations.trim(),followUp:followUp.trim(),status:existing?.status||'completed',photoUri:photoUris[0],photoUris};if(edit&&params.visitId)await Promise.resolve(updateVisit(String(params.visitId),data));else await Promise.resolve(addVisit(data));setMessage(edit?'تم تعديل الزيارة وحفظ التغييرات بنجاح.':'تم حفظ الزيارة بنجاح.');setMessageType('success');setTimeout(()=>router.back(),700);}catch(e){console.error(e);setMessage('حدث خطأ أثناء حفظ الزيارة.');setMessageType('error');}finally{setSaving(false);}};
 const output=(label:string,value:string,placeholder:string)=><View style={styles.block}><Text style={[styles.label,{color:c.foreground}]}>{label}</Text><View style={[styles.output,{backgroundColor:c.card,borderColor:c.border}]}><Text style={[styles.outputText,{color:value?c.foreground:c.mutedForeground}]}>{value||placeholder}</Text></View></View>;
 return <View style={[styles.page,{backgroundColor:c.background}]}><View style={[styles.header,{paddingTop:insets.top+12,borderBottomColor:c.border}]}><Pressable onPress={()=>router.back()} style={styles.back}><Feather name="arrow-right" size={23} color={c.foreground}/></Pressable><Text style={[styles.title,{color:c.foreground}]}>{edit?'تعديل الزيارة':'تسجيل زيارة'}</Text><View style={{width:36}}/></View>
 <KeyboardAwareScrollViewCompat showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingHorizontal:12,paddingBottom:insets.bottom+40}}>
 <Text style={[styles.label,{color:c.foreground}]}>المدرسة</Text><View style={styles.wrap}>{schools.map(s=><Pressable key={s.id} onPress={()=>{setSchoolId(s.id);clearError();}} style={[styles.chip,{backgroundColor:schoolId===s.id?c.primary:c.card,borderColor:schoolId===s.id?c.primary:c.border}]}><Text style={{color:schoolId===s.id?c.primaryForeground:c.foreground,fontFamily:'Inter_500Medium',fontSize:11}}>{s.name}</Text></Pressable>)}</View>{selected?<Text style={[styles.selected,{color:c.mutedForeground}]}>المدرسة المحددة: {selected.name}</Text>:null}
 <Text style={[styles.label,{color:c.foreground}]}>نوع الزيارة</Text><TextInput value={type} onChangeText={setType} placeholder="اكتب نوع الزيارة..." placeholderTextColor={c.mutedForeground} textAlign="right" style={[styles.input,{backgroundColor:c.card,borderColor:c.border,color:c.foreground}]}/>
 <Text style={[styles.label,{color:c.foreground}]}>تاريخ الزيارة</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" placeholderTextColor={c.mutedForeground} textAlign="right" style={[styles.input,{backgroundColor:c.card,borderColor:c.border,color:c.foreground}]}/>
 <View style={[styles.aiCard,{backgroundColor:c.navy}]}><View style={[styles.aiIcon,{backgroundColor:c.accent}]}><Feather name="cpu" size={21} color={c.navy}/></View><View style={{flex:1}}><Text style={styles.aiTitle}>المساعد الذكي للزيارة</Text><Text style={styles.aiSub}>اكتب الإجراءات الفعلية أولًا، ثم سيقدم لك عدة صيغ للتوصيات والمتابعة. الصورة ليست شرطًا.</Text></View><Pressable onPress={openAI} style={[styles.aiButton,{backgroundColor:c.primary}]}><Text style={[styles.aiButtonText,{color:c.primaryForeground}]}>فتح المساعد</Text></Pressable></View>
 {output('الإجراءات المتخذة فعليًا',actions,'سيتم تعبئتها بعد اختيار الصياغة المناسبة من المساعد.')}{output('التوصيات',recommendations,'يمكن للمساعد اقتراح عدة توصيات.')}{output('المتابعة',followUp,'يمكن للمساعد اقتراح عدة صيغ للمتابعة.')}
 <View style={[styles.photoCard,{backgroundColor:c.card,borderColor:c.border}]}><Text style={[styles.label,{color:c.foreground,marginTop:0}]}>صور سجل الزيارة</Text><Text style={[styles.hint,{color:c.mutedForeground}]}>اختيارية بعد الزيارة للتوثيق والرجوع إليها لاحقًا، ولا تمنع استخدام المساعد أو حفظ الزيارة.</Text><View style={styles.photoActions}><Pressable onPress={takePhoto} style={[styles.photoButton,{backgroundColor:c.secondary,borderColor:c.border}]}><Feather name="camera" size={19} color={c.primary}/><Text style={[styles.photoText,{color:c.foreground}]}>تصوير</Text></Pressable><Pressable onPress={addPhotos} style={[styles.photoButton,{backgroundColor:c.secondary,borderColor:c.border}]}><Feather name="image" size={19} color={c.primary}/><Text style={[styles.photoText,{color:c.foreground}]}>اختيار صور</Text></Pressable></View>{photoUris.length?<View style={styles.gallery}>{photoUris.map((u,i)=><View key={`${u}-${i}`} style={styles.thumbWrap}><Pressable onPress={()=>setPreview(u)} style={styles.thumbPress}><Image source={{uri:u}} style={styles.thumb}/></Pressable><Pressable onPress={()=>setPhotoUris(o=>o.filter((_,x)=>x!==i))} style={styles.deleteThumb}><Feather name="x" size={14} color="#FFF"/></Pressable></View>)}</View>:<Text style={[styles.hint,{color:c.mutedForeground}]}>يمكن إرفاق أكثر من صورة.</Text>}</View>
 {message?<View style={[styles.message,{backgroundColor:messageType==='success'?'#E8F7F3':'#FEECEC'}]}><Feather name={messageType==='success'?'check-circle':'alert-circle'} size={18} color={messageType==='success'?c.primary:'#B42318'}/><Text style={{color:messageType==='success'?c.primary:'#B42318',fontFamily:'Inter_600SemiBold',fontSize:11,flex:1}}>{message}</Text></View>:null}
 <Pressable onPress={save} disabled={saving} style={[styles.save,{backgroundColor:c.primary,opacity:saving?.55:1}]}><Feather name="check-circle" size={20} color={c.primaryForeground}/><Text style={{color:c.primaryForeground,fontFamily:'Inter_700Bold',fontSize:13}}>{saving?'جارٍ الحفظ...':edit?'حفظ التعديلات':'حفظ الزيارة'}</Text></Pressable>
 </KeyboardAwareScrollViewCompat><Modal visible={!!preview} animationType="fade" transparent statusBarTranslucent onRequestClose={()=>setPreview(null)}><View style={styles.viewer}><Pressable style={styles.close} onPress={()=>setPreview(null)}><Feather name="x" size={25} color="#FFF"/></Pressable>{preview?<ZoomableImage uri={preview}/>:null}</View></Modal></View>;
}
const styles=StyleSheet.create({page:{flex:1},header:{flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',paddingHorizontal:14,paddingBottom:14,borderBottomWidth:1},back:{width:36,height:36,alignItems:'center',justifyContent:'center'},title:{fontFamily:'Inter_700Bold',fontSize:20},label:{fontFamily:'Inter_600SemiBold',fontSize:12,textAlign:'right',marginTop:15,marginBottom:7},wrap:{flexDirection:'row-reverse',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderRadius:13,paddingHorizontal:13,paddingVertical:10},selected:{fontFamily:'Inter_400Regular',fontSize:10,textAlign:'right',marginTop:7},input:{minHeight:48,borderWidth:1,borderRadius:13,paddingHorizontal:12,paddingVertical:10,fontFamily:'Inter_500Medium',fontSize:12},aiCard:{borderRadius:17,padding:13,marginTop:14,flexDirection:'row-reverse',alignItems:'center',gap:9},aiIcon:{width:42,height:42,borderRadius:13,alignItems:'center',justifyContent:'center'},aiTitle:{color:'#FFF',fontFamily:'Inter_700Bold',fontSize:13,textAlign:'right'},aiSub:{color:'#FFF',opacity:.82,fontFamily:'Inter_400Regular',fontSize:9,lineHeight:16,textAlign:'right',marginTop:3},aiButton:{borderRadius:11,paddingHorizontal:11,paddingVertical:10},aiButtonText:{fontFamily:'Inter_700Bold',fontSize:10},block:{marginTop:2},output:{minHeight:78,borderWidth:1,borderRadius:13,padding:12},outputText:{fontFamily:'Inter_500Medium',fontSize:11,lineHeight:20,textAlign:'right'},photoCard:{borderWidth:1,borderRadius:17,padding:13,marginTop:14},hint:{fontFamily:'Inter_400Regular',fontSize:9,lineHeight:16,textAlign:'right',marginTop:5},photoActions:{flexDirection:'row-reverse',gap:8,marginTop:11},photoButton:{flex:1,minHeight:46,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center',flexDirection:'row-reverse',gap:7},photoText:{fontFamily:'Inter_600SemiBold',fontSize:10},gallery:{flexDirection:'row-reverse',flexWrap:'wrap',gap:8,marginTop:11},thumbWrap:{width:78,height:78,position:'relative'},thumbPress:{width:78,height:78,borderRadius:11,overflow:'hidden'},thumb:{width:'100%',height:'100%'},deleteThumb:{position:'absolute',top:-6,left:-6,width:23,height:23,borderRadius:12,backgroundColor:'#B42318',alignItems:'center',justifyContent:'center'},message:{borderRadius:13,padding:11,flexDirection:'row-reverse',alignItems:'flex-start',gap:7,marginTop:14},save:{minHeight:52,borderRadius:15,alignItems:'center',justifyContent:'center',flexDirection:'row-reverse',gap:8,marginTop:14},viewer:{flex:1,backgroundColor:'rgba(0,0,0,.94)',justifyContent:'center'},close:{position:'absolute',top:45,right:18,zIndex:10,width:42,height:42,borderRadius:21,backgroundColor:'rgba(255,255,255,.18)',alignItems:'center',justifyContent:'center'}});