import React, { useEffect, useMemo, useState } from 'react';
import { Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { useStore, visitTypes } from '@/context/AppContext';
import { KeyboardAwareScrollViewCompat } from '@/components/KeyboardAwareScrollViewCompat';

const asString = (v?: string | string[] | null) => Array.isArray(v) ? v[0] ?? '' : v?.toString() ?? '';
function extractSection(text: string, headings: string[]) { const source = String(text || ''); for (const heading of headings) { const marker = `${heading}:`; const start = source.indexOf(marker); if (start >= 0) { const rest = source.slice(start + marker.length); const next = rest.search(/\n\n(?:الإجراءات المتخذة فعليًا|الإجراءات|الملاحظات|التوصيات|التوصيات والإجراءات المقترحة|المتابعة|خطة المتابعة):/); return (next >= 0 ? rest.slice(0, next) : rest).trim(); } } return ''; }
function parseLegacyActions(text: string) { return { actions: extractSection(text, ['الإجراءات المتخذة فعليًا', 'الإجراءات']), recommendations: extractSection(text, ['التوصيات', 'التوصيات والإجراءات المقترحة']), followUp: extractSection(text, ['المتابعة', 'خطة المتابعة']) }; }
function buildStructuredActions({ actions, recommendations, followUp }: any) { return [['الإجراءات المتخذة فعليًا', actions], ['التوصيات', recommendations], ['المتابعة', followUp]].filter(([,v]) => String(v || '').trim()).map(([h,v]) => `${h}:\n${String(v).trim()}`).join('\n\n'); }

export default function VisitForm() {
  const c = useColors(); const insets = useSafeAreaInsets(); const { schools, visits, addVisit, updateVisit } = useStore();
  const params = useLocalSearchParams<{visitId?: string; schoolId?: string; type?: string; visitType?: string; date?: string; actions?: string; procedure?: string; recommendations?: string; aiActions?: string; aiRecommendations?: string; aiFollowUp?: string}>();
  const isEditMode = Boolean(params.visitId);
  const [schoolId,setSchoolId]=useState(asString(params.schoolId)||schools?.[0]?.id||''); const [type,setType]=useState(asString(params.type||params.visitType)||visitTypes?.[0]||'زيارة اختصاص'); const [date,setDate]=useState(asString(params.date)||new Date().toISOString().slice(0,10));
  const [actions,setActions]=useState(asString(params.actions||params.procedure||params.aiActions)); const [recommendations,setRecommendations]=useState(asString(params.aiRecommendations||params.recommendations)); const [followUp,setFollowUp]=useState(asString(params.aiFollowUp));
  const [photoUris,setPhotoUris]=useState<string[]>([]); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [messageType,setMessageType]=useState<'error'|'success'|''>('');
  const existingVisit=useMemo(()=>params.visitId?visits.find(v=>v.id===String(params.visitId)):undefined,[params.visitId,visits]); const selectedSchool=useMemo(()=>schools.find(s=>s.id===schoolId),[schools,schoolId]); const previousVisits=useMemo(()=>visits.filter(v=>v.schoolId===schoolId&&v.id!==String(params.visitId||'')).sort((a,b)=>b.date.localeCompare(a.date)),[visits,schoolId,params.visitId]); const latestVisit=previousVisits[0];
  useEffect(()=>{if(!existingVisit)return; setSchoolId(String(existingVisit.schoolId));setType(String(existingVisit.type));setDate(String(existingVisit.date));const legacy=parseLegacyActions(String(existingVisit.actions||''));setActions(legacy.actions||String(existingVisit.actions||''));setRecommendations(legacy.recommendations||String((existingVisit as any).recommendations||''));setFollowUp(String((existingVisit as any).followUp||legacy.followUp||''));const photos=Array.isArray((existingVisit as any).photoUris)?(existingVisit as any).photoUris.filter(Boolean).map(String):[];if(existingVisit.photoUri&&!photos.includes(existingVisit.photoUri))photos.unshift(existingVisit.photoUri);setPhotoUris(photos);},[existingVisit]);
  useEffect(()=>{if(params.aiActions!==undefined)setActions(asString(params.aiActions));else if(params.actions!==undefined)setActions(asString(params.actions));else if(params.procedure!==undefined)setActions(asString(params.procedure));if(params.aiRecommendations!==undefined)setRecommendations(asString(params.aiRecommendations));else if(params.recommendations!==undefined)setRecommendations(asString(params.recommendations));if(params.aiFollowUp!==undefined)setFollowUp(asString(params.aiFollowUp));},[params.aiActions,params.aiRecommendations,params.aiFollowUp,params.actions,params.procedure,params.recommendations]);
  const clearMessage=()=>{if(messageType==='error'){setMessage('');setMessageType('');}};
  const addPhotos=async()=>{try{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){setMessage('يرجى السماح للتطبيق بالوصول إلى الصور.');setMessageType('error');return;}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:0.8,allowsMultipleSelection:true,selectionLimit:20});if(!result.canceled&&result.assets?.length){setPhotoUris(old=>Array.from(new Set([...old,...result.assets.map(a=>a.uri)])));clearMessage();}}catch(e){console.error(e);setMessage('تعذر اختيار الصور.');setMessageType('error');}};
  const takePhoto=async()=>{try{const permission=await ImagePicker.requestCameraPermissionsAsync();if(!permission.granted){setMessage('يرجى السماح للتطبيق باستخدام الكاميرا.');setMessageType('error');return;}const result=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:0.8,allowsEditing:true});if(!result.canceled&&result.assets?.[0]?.uri){setPhotoUris(old=>Array.from(new Set([...old,result.assets[0].uri])));clearMessage();}}catch(e){console.error(e);setMessage('تعذر فتح الكاميرا. حاول مرة أخرى.');setMessageType('error');}};
  const openAI=()=>{if(!schoolId){setMessage('يرجى اختيار المدرسة أولاً.');setMessageType('error');return;}router.push({pathname:'/visit-ai',params:{visitId:asString(params.visitId),schoolId:String(schoolId),schoolName:selectedSchool?.name||'',visitType:String(type),type:String(type),date:String(date),actions:String(actions),procedure:String(actions),recommendations:String(recommendations),aiRecommendations:String(recommendations),aiFollowUp:String(followUp)}});};
  const saveVisit=async()=>{if(saving)return;setMessage('');setMessageType('');if(!schoolId){setMessage('يرجى اختيار المدرسة أولاً.');setMessageType('error');return;}if(!date.trim()){setMessage('يرجى إدخال تاريخ الزيارة.');setMessageType('error');return;}if(!type.trim()){setMessage('يرجى اختيار نوع الزيارة.');setMessageType('error');return;}if(!actions.trim()&&!recommendations.trim()&&!followUp.trim()){setMessage('يرجى إدخال الإجراءات أو استخدام المساعد الذكي.');setMessageType('error');return;}try{setSaving(true);const structured=buildStructuredActions({actions,recommendations,followUp});const visitData:any={schoolId:String(schoolId),date:date.trim(),type:type.trim(),actions:structured||actions.trim(),recommendations:recommendations.trim(),followUp:followUp.trim(),status:existingVisit?.status||'completed',photoUri:photoUris[0],photoUris};if(isEditMode&&params.visitId)await Promise.resolve(updateVisit(String(params.visitId),visitData));else await Promise.resolve(addVisit(visitData));setMessage(isEditMode?'تم تعديل الزيارة وحفظ التغييرات بنجاح.':'تم حفظ الزيارة بنجاح.');setMessageType('success');setTimeout(()=>router.back(),700);}catch(e){console.error(e);setMessage('حدث خطأ أثناء حفظ الزيارة.');setMessageType('error');}finally{setSaving(false);}};
  return <View style={[styles.page,{backgroundColor:c.background}]}><View style={[styles.header,{paddingTop:insets.top+12,borderBottomColor:c.border}]}><Pressable onPress={()=>router.back()} style={styles.back}><Feather name="arrow-right" size={23} color={c.foreground}/></Pressable><Text style={[styles.title,{color:c.foreground}]}>{isEditMode?'تعديل الزيارة':'تسجيل زيارة'}</Text><View style={{width:36}}/></View>
  <KeyboardAwareScrollViewCompat showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingHorizontal:12,paddingBottom:insets.bottom+40}}>
    <Text style={[styles.label,{color:c.foreground}]}>المدرسة</Text><View style={styles.wrap}>{schools.map(s=><Pressable key={s.id} onPress={()=>{setSchoolId(s.id);clearMessage();}} style={[styles.chip,{backgroundColor:schoolId===s.id?c.primary:c.card,borderColor:schoolId===s.id?c.primary:c.border}]}><Text style={{color:schoolId===s.id?c.primaryForeground:c.foreground,fontFamily:'Inter_500Medium',fontSize:11}}>{s.name}</Text></Pressable>)}</View>{selectedSchool?<Text style={[styles.selected,{color:c.mutedForeground}]}>المدرسة المحددة: {selectedSchool.name}</Text>:null}
    {latestVisit?<View style={[styles.previous,{backgroundColor:c.secondary,borderColor:c.border}]}><Text style={[styles.previousTitle,{color:c.foreground}]}>آخر زيارة للمدرسة</Text><Text style={[styles.previousText,{color:c.mutedForeground}]}>{latestVisit.date} · {latestVisit.type}</Text><Text style={[styles.previousText,{color:c.foreground}]} numberOfLines={4}>{latestVisit.actions}</Text></View>:null}
    <Text style={[styles.label,{color:c.foreground}]}>نوع الزيارة</Text><View style={styles.wrap}>{visitTypes.map(v=><Pressable key={v} onPress={()=>setType(v)} style={[styles.type,{backgroundColor:type===v?c.secondary:c.card,borderColor:type===v?c.primary:c.border}]}><Text style={{color:type===v?c.primary:c.foreground,fontFamily:'Inter_500Medium',fontSize:11}}>{v}</Text></Pressable>)}</View>
    <Field label="تاريخ الزيارة" value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" c={c}/><Field label="الإجراءات المتخذة فعليًا" value={actions} onChangeText={v=>{setActions(v);clearMessage();}} placeholder="اكتب ما تم القيام به فعليًا أثناء الزيارة..." c={c} multiline/><Field label="التوصيات" value={recommendations} onChangeText={v=>{setRecommendations(v);clearMessage();}} placeholder="اكتب التوصيات المهنية الناتجة عن الزيارة..." c={c} multiline/><Field label="المتابعة" value={followUp} onChangeText={v=>{setFollowUp(v);clearMessage();}} placeholder="اكتب ما ينبغي متابعته لاحقًا..." c={c} multiline/>
    <Pressable onPress={openAI} style={[styles.ai,{backgroundColor:c.navy}]}><View style={[styles.aiIcon,{backgroundColor:c.accent}]}><Feather name="cpu" size={21} color={c.navy}/></View><View style={{flex:1}}><Text style={styles.aiTitle}>المساعد الذكي للزيارة</Text><Text style={styles.aiSub}>يساعد في صياغة التوصيات والمتابعة اعتمادًا على بيانات الزيارة، والمشرف يراجع ويعتمد</Text></View><Feather name="chevron-left" size={19} color="#FFF"/></Pressable>
    <View style={styles.photoActions}><Pressable onPress={takePhoto} style={[styles.photoButton,{backgroundColor:c.secondary,borderColor:c.border}]}><Feather name="camera" size={19} color={c.primary}/><Text style={[styles.photoButtonText,{color:c.foreground}]}>تصوير</Text></Pressable><Pressable onPress={addPhotos} style={[styles.photoButton,{backgroundColor:c.secondary,borderColor:c.border}]}><Feather name="image" size={19} color={c.primary}/><Text style={[styles.photoButtonText,{color:c.foreground}]}>اختيار صور</Text></Pressable></View>
    {photoUris.length>0?<View style={styles.gallery}>{photoUris.map((uri,i)=><View key={`${uri}-${i}`} style={styles.thumbWrap}><Image source={{uri}} style={styles.thumb}/><Pressable onPress={()=>setPhotoUris(old=>old.filter((_,x)=>x!==i))} style={styles.deleteThumb}><Feather name="x" size={14} color="#FFF"/></Pressable></View>)}</View>:<Text style={[styles.photoHint,{color:c.mutedForeground}]}>يمكن إرفاق أكثر من صورة للزيارة.</Text>}
    {message?<View style={[styles.message,{backgroundColor:messageType==='success'?'#E8F7F3':'#FEECEC'}]}><Feather name={messageType==='success'?'check-circle':'alert-circle'} size={18} color={messageType==='success'?c.primary:'#B42318'}/><Text style={{color:messageType==='success'?c.primary:'#B42318',fontFamily:'Inter_600SemiBold',fontSize:11}}>{message}</Text></View>:null}
    <Pressable onPress={saveVisit} disabled={saving} style={[styles.save,{backgroundColor:c.primary,opacity:saving?.55:1}]}><Feather name="check-circle" size={20} color={c.primaryForeground}/><Text style={{color:c.primaryForeground,fontFamily:'Inter_700Bold',fontSize:13}}>{saving?'جارٍ الحفظ...':isEditMode?'حفظ التعديلات':'حفظ الزيارة'}</Text></Pressable>
  </KeyboardAwareScrollViewCompat></View>;
}
function Field({label,value,onChangeText,placeholder,multiline=false,c}:any){return <View><Text style={[styles.label,{color:c.foreground}]}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={c.mutedForeground} multiline={multiline} textAlign="right" textAlignVertical={multiline?'top':'center'} style={[styles.input,{backgroundColor:c.card,borderColor:c.border,color:c.foreground,minHeight:multiline?110:48}]}/></View>}
const styles=StyleSheet.create({page:{flex:1},header:{flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',paddingHorizontal:14,paddingBottom:14,borderBottomWidth:1},back:{width:36,height:36,alignItems:'center',justifyContent:'center'},title:{fontFamily:'Inter_700Bold',fontSize:20},label:{fontFamily:'Inter_600SemiBold',fontSize:12,textAlign:'right',marginTop:12,marginBottom:8},wrap:{flexDirection:'row-reverse',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderRadius:12,paddingHorizontal:12,paddingVertical:10},selected:{fontSize:9,textAlign:'right',marginTop:5},previous:{borderWidth:1,borderRadius:16,padding:12,marginTop:12},previousTitle:{fontFamily:'Inter_700Bold',fontSize:12,textAlign:'right'},previousText:{fontFamily:'Inter_400Regular',fontSize:10,textAlign:'right',marginTop:5,lineHeight:18},type:{borderWidth:1,borderRadius:11,paddingHorizontal:10,paddingVertical:9},input:{borderWidth:1,borderRadius:13,paddingHorizontal:13,paddingVertical:11,fontFamily:'Inter_400Regular',fontSize:13,marginBottom:3,lineHeight:21},ai:{minHeight:72,borderRadius:17,paddingHorizontal:13,flexDirection:'row-reverse',alignItems:'center',gap:10,marginTop:16,marginBottom:14},aiIcon:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center'},aiTitle:{color:'#FFF',fontFamily:'Inter_700Bold',fontSize:12,textAlign:'right'},aiSub:{color:'#B7D9D4',fontFamily:'Inter_400Regular',fontSize:9,textAlign:'right',marginTop:3,lineHeight:15},photoActions:{flexDirection:'row-reverse',gap:8,marginTop:4},photoButton:{flex:1,minHeight:48,borderWidth:1,borderRadius:14,flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',gap:7},photoButtonText:{fontFamily:'Inter_600SemiBold',fontSize:11},gallery:{flexDirection:'row-reverse',flexWrap:'wrap',gap:8,marginTop:10},thumbWrap:{width:92,height:92,borderRadius:12,overflow:'visible'},thumb:{width:92,height:92,borderRadius:12},deleteThumb:{position:'absolute',top:-5,left:-5,width:23,height:23,borderRadius:12,backgroundColor:'#B42318',alignItems:'center',justifyContent:'center'},photoHint:{fontSize:10,textAlign:'right',marginTop:7},message:{minHeight:46,borderRadius:13,padding:10,flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',gap:8,marginTop:14},save:{minHeight:55,borderRadius:15,flexDirection:'row-reverse',alignItems:'center',justifyContent:'center',gap:8,marginTop:14}});
