import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useColors } from '@/hooks/useColors';
import { useStore, statusLabels } from '@/context/AppContext';

export default function Home() {
 const c = useColors(); const insets = useSafeAreaInsets(); const { schools, visits, tasks } = useStore();
 const completed = visits.filter(v => v.status === 'completed').length; const planned = visits.filter(v => v.status === 'planned').length; const todayTasks = tasks.filter(t => t.date === '2026-08-20');
 return <ScrollView style={{ backgroundColor: c.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: 110 }]} showsVerticalScrollIndicator={false}>
   <View style={styles.top}><View><Text style={[styles.eyebrow, { color: c.primary }]}>نظام الإشراف التربوي</Text><Text style={[styles.greeting, { color: c.foreground }]}>صباح الخير، أستاذ ضرغام</Text></View><View style={[styles.avatar, { backgroundColor: c.secondary }]}><Feather name="briefcase" size={23} color={c.primary} /></View></View>
   <View style={[styles.hero, { backgroundColor: c.navy }]}><View style={{ flex: 1 }}><Text style={styles.heroKicker}>المتابعة اليومية</Text><Text style={styles.heroTitle}>سجّل زياراتك بوضوح، وابقَ قريباً من كل مدرسة.</Text><Text style={styles.heroSub}>إدارة السجلات والملاحظات من مكان واحد</Text></View><View style={[styles.heroIcon, { backgroundColor: c.accent }]}><Feather name="map" size={31} color={c.navy} /></View></View>
   <View style={styles.metrics}><Metric icon="home" label="المدارس" value={schools.length} c={c} /><Metric icon="check-circle" label="زيارات الشهر" value={completed} c={c} /><Metric icon="clock" label="مخططة" value={planned} c={c} /></View>
   <View style={styles.sectionHead}><Text style={[styles.sectionTitle, { color: c.foreground }]}>إجراءات سريعة</Text></View>
   <View style={styles.quickGrid}>
     <Quick icon="plus-square" label="إضافة مدرسة" onPress={() => router.push('/school-form')} c={c} />
     <Quick icon="camera" label="تسجيل زيارة" onPress={() => router.push('/visit-form')} c={c} />
     <Quick icon="calendar" label="جدولة عمل" onPress={() => router.push('/task-form')} c={c} />
     <Quick icon="book-open" label="التشريعات" onPress={() => router.push('/legislation')} c={c} />
   </View>
   <View style={styles.sectionHead}><Text style={[styles.sectionTitle, { color: c.foreground }]}>زيارات هذا الشهر</Text><Pressable onPress={() => router.push('/(tabs)/visits')}><Text style={{ color: c.primary, fontFamily: 'Inter_600SemiBold' }}>عرض الكل</Text></Pressable></View>
   {visits.slice(0, 3).map(v => { const school = schools.find(s => s.id === v.schoolId); return <View key={v.id} style={[styles.visitRow, { backgroundColor: c.card, borderColor: c.border }]}><View style={[styles.dateBox, { backgroundColor: c.secondary }]}><Text style={[styles.dateDay, { color: c.primary }]}>{v.date.slice(-2)}</Text><Text style={[styles.dateMonth, { color: c.mutedForeground }]}>آب</Text></View><View style={{ flex: 1 }}><Text style={[styles.rowTitle, { color: c.foreground }]}>{school?.name}</Text><Text style={[styles.rowSub, { color: c.mutedForeground }]}>{v.type} · {v.date}</Text></View><Status status={v.status} c={c} /></View> })}
   <View style={[styles.offline, { backgroundColor: c.secondary }]}><Feather name="wifi-off" size={17} color={c.primary} /><Text style={{ color: c.secondaryForeground, fontFamily: 'Inter_500Medium', flex: 1 }}>تعمل دون إنترنت · ستتم مزامنة البيانات عند توفر الاتصال</Text></View>
   <Text style={[styles.credit, { color: c.mutedForeground }]}>تصميم وبرمجة: الاختصاص التربوي ضرغام مهدي</Text>
 </ScrollView>;
}
function Metric({ icon, label, value, c }: any) { return <View style={[styles.metric, { backgroundColor: c.card, borderColor: c.border }]}><Feather name={icon} size={18} color={c.primary} /><Text style={[styles.metricValue, { color: c.foreground }]}>{value}</Text><Text style={[styles.metricLabel, { color: c.mutedForeground }]}>{label}</Text></View>; }
function Quick({ icon, label, onPress, c }: any) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.quick, { backgroundColor: c.secondary, opacity: pressed ? .7 : 1 }]}><Feather name={icon} size={21} color={c.primary} /><Text style={{ color: c.secondaryForeground, fontFamily: 'Inter_600SemiBold', marginTop: 7, fontSize: 11 }}>{label}</Text></Pressable>; }
function Status({ status, c }: any) { return <View style={[styles.status, { backgroundColor: status === 'completed' ? '#E5F4EC' : status === 'postponed' ? '#FFF2DD' : c.secondary }]}><Text style={{ color: status === 'completed' ? c.success : status === 'postponed' ? c.warning : c.primary, fontFamily: 'Inter_600SemiBold', fontSize: 11 }}>{statusLabels[status as keyof typeof statusLabels]}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 18 }, top: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', marginBottom: 18 }, eyebrow: { fontSize: 12, fontFamily: 'Inter_600SemiBold', textAlign: 'right' }, greeting: { fontSize: 20, fontFamily: 'Inter_700Bold', textAlign: 'right', marginTop: 5 }, avatar: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, hero: { borderRadius: 24, padding: 20, flexDirection: 'row-reverse', alignItems: 'center', gap: 12, minHeight: 158 }, heroKicker: { color: '#B7D9D4', fontSize: 12, fontFamily: 'Inter_600SemiBold', textAlign: 'right', marginBottom: 9 }, heroTitle: { color: '#FFFFFF', fontSize: 18, lineHeight: 27, fontFamily: 'Inter_700Bold', textAlign: 'right' }, heroSub: { color: '#B7D9D4', fontSize: 11, fontFamily: 'Inter_400Regular', textAlign: 'right', marginTop: 9 }, heroIcon: { width: 52, height: 52, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, metrics: { flexDirection: 'row-reverse', gap: 8, marginTop: 14 }, metric: { flex: 1, borderRadius: 16, borderWidth: 1, padding: 11, alignItems: 'center', minHeight: 84 }, metricValue: { fontSize: 20, fontFamily: 'Inter_700Bold', marginTop: 4 }, metricLabel: { fontSize: 10, fontFamily: 'Inter_500Medium', marginTop: 3 }, sectionHead: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', marginTop: 22, marginBottom: 10 }, sectionTitle: { fontSize: 16, fontFamily: 'Inter_700Bold' }, quickGrid: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8 }, quick: { width: '48%', borderRadius: 17, padding: 12, alignItems: 'center', minHeight: 78 }, visitRow: { borderRadius: 17, borderWidth: 1, padding: 11, flexDirection: 'row-reverse', alignItems: 'center', marginBottom: 9, gap: 10 }, dateBox: { width: 45, height: 50, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, dateDay: { fontFamily: 'Inter_700Bold', fontSize: 17 }, dateMonth: { fontFamily: 'Inter_500Medium', fontSize: 10 }, rowTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 13, textAlign: 'right' }, rowSub: { fontFamily: 'Inter_400Regular', fontSize: 10, textAlign: 'right', marginTop: 4 }, status: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8 }, offline: { marginTop: 17, borderRadius: 14, padding: 12, flexDirection: 'row-reverse', alignItems: 'center', gap: 8 }, credit: { textAlign: 'center', fontSize: 10, fontFamily: 'Inter_400Regular', marginTop: 20 } });
