import React from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useColors } from '@/hooks/useColors';
import { useStore } from '@/context/AppContext';
export default function Schools() { const c = useColors(); const insets = useSafeAreaInsets(); const { schools } = useStore(); return <View style={[styles.page, { backgroundColor: c.background, paddingTop: insets.top + 18 }]}><View style={styles.header}><View><Text style={[styles.kicker, { color: c.primary }]}>سجل المدارس</Text><Text style={[styles.title, { color: c.foreground }]}>مدارسي</Text></View><Pressable onPress={() => router.push('/school-form')} style={[styles.add, { backgroundColor: c.primary }]}><Feather name="plus" size={22} color={c.primaryForeground} /></Pressable></View><Text style={[styles.count, { color: c.mutedForeground }]}>{schools.length} مدارس ضمن إشرافك هذا الشهر</Text><FlatList data={schools} keyExtractor={x => x.id} contentContainerStyle={{ paddingTop: 16, paddingBottom: 110 }} scrollEnabled={schools.length > 0} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: '/school-detail', params: { id: item.id } })} style={({ pressed }) => [styles.card, { backgroundColor: c.card, borderColor: c.border, opacity: pressed ? .75 : 1 }]}><View style={[styles.schoolIcon, { backgroundColor: c.secondary }]}><Feather name="home" size={21} color={c.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: c.foreground }]}>{item.name}</Text><Text style={[styles.sub, { color: c.mutedForeground }]}>{item.address}</Text><View style={styles.tags}>{item.sections.map(s => <View key={s} style={[styles.tag, { backgroundColor: c.secondary }]}><Text style={{ color: c.secondaryForeground, fontFamily: 'Inter_500Medium', fontSize: 10 }}>{s}</Text></View>)}</View></View><Feather name="chevron-left" size={18} color={c.mutedForeground} /></Pressable>} ListEmptyComponent={<View style={styles.empty}><Feather name="home" size={34} color={c.mutedForeground} /><Text style={{ color: c.mutedForeground, fontFamily: 'Inter_500Medium', marginTop: 10 }}>لا توجد مدارس بعد</Text></View>} /></View>; }
const styles = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 18 }, header: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' }, kicker: { fontFamily: 'Inter_600SemiBold', fontSize: 12, textAlign: 'right' }, title: { fontFamily: 'Inter_700Bold', fontSize: 26, textAlign: 'right', marginTop: 5 }, add: { width: 46, height: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, count: { fontFamily: 'Inter_400Regular', fontSize: 12, textAlign: 'right', marginTop: 8 }, card: { borderWidth: 1, borderRadius: 18, padding: 13, flexDirection: 'row-reverse', alignItems: 'center', gap: 10, marginBottom: 10 }, schoolIcon: { width: 46, height: 46, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, name: { fontFamily: 'Inter_700Bold', fontSize: 14, textAlign: 'right' }, sub: { fontFamily: 'Inter_400Regular', fontSize: 11, textAlign: 'right', marginTop: 4 }, tags: { flexDirection: 'row-reverse', gap: 4, marginTop: 8, flexWrap: 'wrap' }, tag: { borderRadius: 6, paddingHorizontal: 7, paddingVertical: 4 }, empty: { alignItems: 'center', justifyContent: 'center', paddingTop: 120 } });
