import React, { useMemo } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useColors } from '@/hooks/useColors';
import { useStore } from '@/context/AppContext';
export default function Tasks() { const c = useColors(); const insets = useSafeAreaInsets(); const { tasks, schools, toggleTask } = useStore(); const today = useMemo(() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }, []); return <View style={[styles.page, { backgroundColor: c.background, paddingTop: insets.top + 18 }]}><View style={styles.header}><View><Text style={[styles.kicker, { color: c.primary }]}>تنظيم اليوم</Text><Text style={[styles.title, { color: c.foreground }]}>الأعمال اليومية</Text></View><Pressable onPress={() => router.push('/task-form')} style={[styles.add, { backgroundColor: c.primary }]}><Feather name="plus" size={22} color={c.primaryForeground} /></Pressable></View><Text style={[styles.count, { color: c.mutedForeground }]}>أعمال اليوم</Text><FlatList data={tasks.filter(t => t.date === today)} keyExtractor={x => x.id} contentContainerStyle={{ paddingTop: 16, paddingBottom: 110 }} scrollEnabled={tasks.length > 0} renderItem={({ item }) => <Pressable onPress={() => toggleTask(item.id)} style={[styles.card, { backgroundColor: c.card, borderColor: c.border, opacity: item.done ? .65 : 1 }]}><View style={[styles.check, { borderColor: item.done ? c.success : c.border, backgroundColor: item.done ? c.success : c.card }]}>{item.done && <Feather name="check" size={15} color={c.primaryForeground} />}</View><View style={{ flex: 1 }}><Text style={[styles.task, { color: c.foreground, textDecorationLine: item.done ? 'line-through' : 'none' }]}>{item.title}</Text><Text style={[styles.detail, { color: c.mutedForeground }]}>{item.schoolId ? schools.find(s => s.id === item.schoolId)?.name : 'عمل إداري'} · {item.time}</Text><Text style={[styles.note, { color: c.mutedForeground }]}>{item.notes}</Text></View><View style={[styles.priority, { backgroundColor: item.priority === 'high' ? '#FBE5E5' : item.priority === 'medium' ? '#FFF2DD' : c.secondary }]}><Text style={{ color: item.priority === 'high' ? c.destructive : item.priority === 'medium' ? c.warning : c.primary, fontFamily: 'Inter_600SemiBold', fontSize: 10 }}>{item.priority === 'high' ? 'عالية' : item.priority === 'medium' ? 'متوسطة' : 'منخفضة'}</Text></View></Pressable>} ListEmptyComponent={<View style={styles.empty}><Feather name="check-circle" size={34} color={c.mutedForeground} /><Text style={{ color: c.mutedForeground, fontFamily: 'Inter_500Medium', marginTop: 10 }}>لا توجد أعمال لهذا اليوم</Text></View>} /></View>; }
const styles = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 18 }, header: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' }, kicker: { fontFamily: 'Inter_600SemiBold', fontSize: 12, textAlign: 'right' }, title: { fontFamily: 'Inter_700Bold', fontSize: 24, textAlign: 'right', marginTop: 5 }, add: { width: 46, height: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, count: { fontFamily: 'Inter_400Regular', fontSize: 12, textAlign: 'right', marginTop: 8 }, card: { borderWidth: 1, borderRadius: 18, padding: 13, flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 10, marginBottom: 10 }, check: { width: 27, height: 27, borderRadius: 9, borderWidth: 2, alignItems: 'center', justifyContent: 'center', marginTop: 1 }, task: { fontFamily: 'Inter_700Bold', fontSize: 13, textAlign: 'right' }, detail: { fontFamily: 'Inter_400Regular', fontSize: 10, textAlign: 'right', marginTop: 5 }, note: { fontFamily: 'Inter_400Regular', fontSize: 10, textAlign: 'right', marginTop: 6 }, priority: { borderRadius: 7, paddingHorizontal: 7, paddingVertical: 5 }, empty: { alignItems: 'center', justifyContent: 'center', paddingTop: 120 } });
