import React from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useColors } from '@/hooks/useColors';
import { useStore, statusLabels } from '@/context/AppContext';
export default function Visits() { const c = useColors(); const insets = useSafeAreaInsets(); const { visits, schools } = useStore(); return <View style={[styles.page, { backgroundColor: c.background, paddingTop: insets.top + 18 }]}><View style={styles.header}><View><Text style={[styles.kicker, { color: c.primary }]}>سجل المتابعة</Text><Text style={[styles.title, { color: c.foreground }]}>الزيارات</Text></View><Pressable onPress={() => router.push('/visit-form')} style={[styles.add, { backgroundColor: c.primary }]}><Feather name="camera" size={21} color={c.primaryForeground} /></Pressable></View><View style={[styles.filter, { backgroundColor: c.secondary }]}><Feather name="calendar" size={16} color={c.primary} /><Text style={{ color: c.secondaryForeground, fontFamily: 'Inter_600SemiBold', fontSize: 12 }}>آب 2026</Text><Text style={{ color: c.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 11, marginRight: 'auto' }}>{visits.length} زيارة</Text></View><FlatList data={visits} keyExtractor={x => x.id} contentContainerStyle={{ paddingTop: 13, paddingBottom: 110 }} scrollEnabled={visits.length > 0} renderItem={({ item }) => { const school = schools.find(s => s.id === item.schoolId); const color = item.status === 'completed' ? c.success : item.status === 'postponed' ? c.warning : c.primary; return <View style={[styles.card, { backgroundColor: c.card, borderColor: c.border }]}><View style={[styles.visitIcon, { backgroundColor: c.secondary }]}><Feather name={item.photoUri ? 'image' : 'clipboard'} size={20} color={c.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.school, { color: c.foreground }]}>{school?.name}</Text><Text style={[styles.details, { color: c.mutedForeground }]}>{item.type} · {item.date}</Text><Text style={[styles.reason, { color: c.foreground }]}>{item.reason}</Text></View><View style={[styles.status, { backgroundColor: item.status === 'completed' ? '#E5F4EC' : item.status === 'postponed' ? '#FFF2DD' : c.secondary }]}><Text style={{ color, fontFamily: 'Inter_600SemiBold', fontSize: 10 }}>{statusLabels[item.status]}</Text></View></View> }} ListEmptyComponent={<View style={styles.empty}><Feather name="camera" size={34} color={c.mutedForeground} /><Text style={{ color: c.mutedForeground, fontFamily: 'Inter_500Medium', marginTop: 10 }}>لا توجد زيارات مسجلة</Text></View>} /></View>; }
const styles = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 18 }, header: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' }, kicker: { fontFamily: 'Inter_600SemiBold', fontSize: 12, textAlign: 'right' }, title: { fontFamily: 'Inter_700Bold', fontSize: 26, textAlign: 'right', marginTop: 5 }, add: { width: 46, height: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, filter: { marginTop: 18, borderRadius: 13, padding: 11, flexDirection: 'row-reverse', alignItems: 'center', gap: 8 }, card: { borderWidth: 1, borderRadius: 18, padding: 13, flexDirection: 'row-reverse', alignItems: 'center', gap: 10, marginBottom: 10 }, visitIcon: { width: 44, height: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, school: { fontFamily: 'Inter_700Bold', fontSize: 13, textAlign: 'right' }, details: { fontFamily: 'Inter_400Regular', fontSize: 10, textAlign: 'right', marginTop: 4 }, reason: { fontFamily: 'Inter_500Medium', fontSize: 11, textAlign: 'right', marginTop: 6 }, status: { borderRadius: 8, paddingHorizontal: 7, paddingVertical: 5 }, empty: { alignItems: 'center', justifyContent: 'center', paddingTop: 120 } });
